exina_admin_homepage:
    pattern:  /
    defaults: { _controller: ExinaAdminBundle:Default:index }
ex_admin_key_home:
    pattern: /key/
    defaults: {_controller: ExinaAdminBundle:Key:list }
ex_admin_key_list:
    pattern: /key/
    defaults: {_controller: ExinaAdminBundle:Key:list }
ex_admin_key_new:
    pattern: /key/new
    defaults: {_controller: ExinaAdminBundle:Key:create }
ex_admin_key_update:
    pattern: /key/update/{id}
    defaults: { _controller: ExinaAdminBundle:Key:update }
    requirements:
        id: \d+
ex_admin_key_delete:
    pattern: /key/delete/{id}
    defaults: { _controller: ExinaAdminBundle:Key:delete }
    requirements:
        id: \d+

ex_admin_product_home:
    pattern: /product/
    defaults: {_controller: ExinaAdminBundle:Product:list }
ex_admin_product_list:
    pattern: /product/
    defaults: {_controller: ExinaAdminBundle:Product:list }
ex_admin_product_new:
    pattern: /product/new
    defaults: {_controller: ExinaAdminBundle:Product:create }
ex_admin_product_update:
    pattern: /product/update/{id}
    defaults: { _controller: ExinaAdminBundle:Product:update }
    requirements:
        id: \d+
ex_admin_product_delete:
    pattern: /product/delete/{id}
    defaults: { _controller: ExinaAdminBundle:Product:delete }
    requirements:
        id: \d+
